version: "3"
services:
  app:
    build: .
    ports:
      - '3030:3030'
    volumes:
      - .:/app
    command: "air -c .air.toml"
    depends_on:
      - db
  db:
    image: mysql:8.0.21
    platform: linux/x86_64
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql:cached
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
volumes:
  db_data:
